language: node_js
node_js:
- '12'
install: npm install
script: npm run build
sudo: false
cache: npm

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
