/** Declaration file generated by dts-gen */

interface LoopProtect {

    alias: string;

    debug(enable:boolean): void;

    protect(line:number, reset?: boolean): any;

    reset(): void;

    rewriteLoops(code: string, offset?: number): any;

}

declare var loopProtect:LoopProtect;